filmMakerRepository ,FilmMakerDTO , FilmMakerNotFoundExeption done
SardorSohinazarov/AsilMedia pull request #16
Opened 2024-02-26 04:48 UTC by Tursunboev0227

close #1

2024-02-26 05:03 UTC, Tohirjon-Odilov requested changes
Ogohlantirish

2024-02-26 05:03 UTC, Tohirjon-Odilov commented on src/Core/AsilMedia.Application/DataTransferObjects/FilmMakerDTO.cs
> +
Nimga bu list yetim qilib ajratib qo'ydingiz. Sababini kutamiz

2024-02-26 05:03 UTC, Tohirjon-Odilov commented on src/Core/AsilMedia.Domain/Exceptions/FilmMakers/FilmMakerNotFoundExeption.cs
> +        public FilmMakerNotFoundException() : base("FilmMaker not found.") { }
Exception'ku bu FilmMaker => Film maker qilsangiz ham bo'ladi

2024-02-26 05:03 UTC, Tohirjon-Odilov commented on src/External/AsilMedia.Infrastructure/Repositories/FilmMakerRepository.cs
> +            ///...
Comment qolib ketibdi

2024-02-26 06:41 UTC, Tursunboev0227 commented on src/Core/AsilMedia.Application/DataTransferObjects/FilmMakerDTO.cs
> +
Shunchaki tab tab

2024-02-27 03:08 UTC, SardorSohinazarov approved these changes

2024-02-27 03:09 UTC, merged